# Generated by Django 4.2.9 on 2026-02-25 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('correspondencia', '0002_documento_hora_radicacion_alter_documento_actor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('OF', 'Oficio'), ('MM', 'Memorando'), ('CR', 'Circular'), ('RS', 'Resolución'), ('AC', 'Acta')], max_length=2, unique=True, verbose_name='Tipo de documento')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la plantilla')),
                ('encabezado', models.TextField(blank=True, verbose_name='Texto de encabezado / considerandos')),
                ('cuerpo', models.TextField(verbose_name='Cuerpo del documento (plantilla base)')),
                ('pie', models.TextField(blank=True, verbose_name='Texto de cierre / pie')),
                ('activa', models.BooleanField(default=True, verbose_name='Plantilla activa')),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Plantilla',
                'verbose_name_plural': 'Plantillas',
            },
        ),
        migrations.CreateModel(
            name='DocumentoGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido final del documento')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='plantillas/generados/', verbose_name='Archivo PDF generado')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs_generados', to='correspondencia.documento', verbose_name='Documento radicado')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('plantilla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantillas.plantilladocumento', verbose_name='Plantilla usada')),
            ],
            options={
                'verbose_name': 'Documento generado',
                'verbose_name_plural': 'Documentos generados',
                'ordering': ['-fecha'],
            },
        ),
    ]
