databases:
  - name: cer-db
    databaseName: cer_correspondencia
    user: cer_user
    plan: free

services:
  - type: web
    name: cer-correspondencia
    plan: free
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py verificar_produccion --fail-on-error"
    startCommand: "python manage.py migrate && gunicorn config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: cer-db
          property: internalConnectionString
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: REDIS_URL
        value: ""
      - key: SENTRY_DSN
        value: ""
      - key: EMAIL_HOST_USER
        value: ""
      - key: EMAIL_HOST_PASSWORD
        value: ""
