# Generated by Django 4.2.9 on 2026-02-24 22:44

import correspondencia.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radicado', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numero de radicado')),
                ('consecutivo_anio', models.PositiveIntegerField(editable=False, verbose_name='Consecutivo del anio')),
                ('tipo', models.CharField(choices=[('OF', 'Oficio'), ('MM', 'Memorando'), ('CR', 'Circular'), ('RS', 'Resolucion'), ('AC', 'Acta')], max_length=2, verbose_name='Tipo de documento')),
                ('flujo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10, verbose_name='Flujo')),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('confidencial', 'Confidencial')], default='normal', max_length=15, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('en_tramite', 'En Tramite'), ('respondido', 'Respondido'), ('archivado', 'Archivado')], default='recibido', max_length=15, verbose_name='Estado')),
                ('actor', models.CharField(choices=[('gremio', 'Gremio'), ('agroindustria', 'Agroindustria'), ('cooperativa', 'Cooperativa'), ('educacion', 'Institucion Educativa'), ('camara', 'Camara de Comercio'), ('dian', 'DIAN'), ('entidad_publica', 'Entidad Publica'), ('sector_privado', 'Sector Privado'), ('interno', 'Interno CER'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Actor del ecosistema')),
                ('remitente', models.CharField(max_length=200, verbose_name='Remitente')),
                ('destinatario', models.CharField(max_length=200, verbose_name='Destinatario')),
                ('entidad', models.CharField(blank=True, max_length=200, verbose_name='Entidad')),
                ('asunto', models.CharField(max_length=500, verbose_name='Asunto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('archivo', models.FileField(blank=True, null=True, upload_to=correspondencia.models.ruta_documento, verbose_name='Archivo digital')),
                ('fecha_radicacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de radicacion')),
                ('fecha_documento', models.DateField(blank=True, null=True, verbose_name='Fecha del documento')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha limite de respuesta')),
                ('fecha_respuesta', models.DateField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('documento_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='correspondencia.documento', verbose_name='En respuesta a')),
                ('radicado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_radicados', to=settings.AUTH_USER_MODEL, verbose_name='Radicado por')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_radicacion', '-consecutivo_anio'],
            },
        ),
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('recibido', 'Recibido'), ('en_tramite', 'En Tramite'), ('respondido', 'Respondido'), ('archivado', 'Archivado')], max_length=15)),
                ('estado_nuevo', models.CharField(choices=[('recibido', 'Recibido'), ('en_tramite', 'En Tramite'), ('respondido', 'Respondido'), ('archivado', 'Archivado')], max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField(blank=True, verbose_name='Observacion del cambio')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trazabilidad', to='correspondencia.documento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trazabilidad',
                'verbose_name_plural': 'Trazabilidad',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['radicado'], name='corresponde_radicad_f39b10_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['fecha_radicacion'], name='corresponde_fecha_r_92de63_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['estado'], name='corresponde_estado_4bb561_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['remitente'], name='corresponde_remiten_523ed2_idx'),
        ),
    ]
