# Generated by Django 4.2.9 on 2026-02-25 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='hora_radicacion',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de radicación'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='actor',
            field=models.CharField(choices=[('gremio', 'Gremio'), ('agroindustria', 'Agroindustria'), ('cooperativa', 'Cooperativa'), ('educacion', 'Institución Educativa'), ('camara', 'Cámara de Comercio'), ('dian', 'DIAN'), ('entidad_publica', 'Entidad Pública'), ('sector_privado', 'Sector Privado'), ('interno', 'Interno CER'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Actor del ecosistema'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='consecutivo_anio',
            field=models.PositiveIntegerField(editable=False, verbose_name='Consecutivo del año'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción / Observaciones'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='entidad',
            field=models.CharField(blank=True, max_length=200, verbose_name='Entidad / Organización'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('recibido', 'Recibido'), ('en_tramite', 'En Trámite'), ('respondido', 'Respondido'), ('archivado', 'Archivado')], default='recibido', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite de respuesta'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_radicacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de radicación'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='radicado',
            field=models.CharField(editable=False, max_length=30, unique=True, verbose_name='Número de radicado'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('OF', 'Oficio'), ('MM', 'Memorando'), ('CR', 'Circular'), ('RS', 'Resolución'), ('AC', 'Acta')], max_length=2, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='trazabilidad',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('recibido', 'Recibido'), ('en_tramite', 'En Trámite'), ('respondido', 'Respondido'), ('archivado', 'Archivado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='trazabilidad',
            name='estado_nuevo',
            field=models.CharField(choices=[('recibido', 'Recibido'), ('en_tramite', 'En Trámite'), ('respondido', 'Respondido'), ('archivado', 'Archivado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='trazabilidad',
            name='nota',
            field=models.TextField(blank=True, verbose_name='Observación del cambio'),
        ),
    ]
