# Generated by Django 4.2.9 on 2026-03-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0002_documento_hora_radicacion_alter_documento_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='actor',
            field=models.CharField(choices=[('gremio', 'Gremio'), ('agroindustria', 'Agroindustria'), ('cooperativa', 'Cooperativa'), ('educacion', 'Institución Educativa'), ('camara', 'Cámara de Comercio'), ('dian', 'DIAN'), ('entidad_publica', 'Entidad Pública'), ('sector_privado', 'Sector Privado'), ('interno', 'Interno CER'), ('otro', 'Otro')], db_index=True, default='otro', max_length=20, verbose_name='Actor del ecosistema'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('recibido', 'Recibido'), ('en_tramite', 'En Trámite'), ('respondido', 'Respondido'), ('archivado', 'Archivado')], db_index=True, default='recibido', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_limite',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha límite de respuesta'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='flujo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], db_index=True, max_length=10, verbose_name='Flujo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='prioridad',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('confidencial', 'Confidencial')], db_index=True, default='normal', max_length=15, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('OF', 'Oficio'), ('MM', 'Memorando'), ('CR', 'Circular'), ('RS', 'Resolución'), ('AC', 'Acta')], db_index=True, max_length=2, verbose_name='Tipo de documento'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tipo'], name='corresponde_tipo_01f2ea_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['flujo'], name='corresponde_flujo_586e33_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['prioridad'], name='corresponde_priorid_d510fd_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['fecha_limite'], name='corresponde_fecha_l_026071_idx'),
        ),
    ]
