# Generated by Django 4.2.9 on 2026-03-29 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0003_alter_documento_actor_alter_documento_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-fecha_radicacion', '-consecutivo_anio'], 'permissions': [('view_confidenciales', 'Puede ver documentos confidenciales')], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
    ]
