# Generated by Django 4.2.9 on 2026-03-29 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('correspondencia', '0004_alter_documento_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=100, verbose_name='Serie documental')),
                ('subserie', models.CharField(blank=True, max_length=100, verbose_name='Subserie')),
                ('tipo_documental', models.CharField(choices=[('OF', 'Oficio'), ('MM', 'Memorando'), ('CR', 'Circular'), ('RS', 'Resolución'), ('AC', 'Acta')], max_length=2, verbose_name='Tipo de documento')),
                ('retencion_gestion', models.PositiveIntegerField(verbose_name='Años en archivo de gestión')),
                ('retencion_central', models.PositiveIntegerField(verbose_name='Años en archivo central')),
                ('disposicion_final', models.CharField(choices=[('CT', 'Conservar Total'), ('E', 'Eliminar'), ('S', 'Selección'), ('D', 'Digital')], max_length=2, verbose_name='Disposición final')),
                ('procedimiento', models.TextField(blank=True, verbose_name='Procedimiento de aplicación')),
                ('activo', models.BooleanField(default=True, verbose_name='TRD activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tabla de Retención Documental',
                'verbose_name_plural': 'Tablas de Retención Documental',
                'ordering': ['serie', 'subserie'],
                'unique_together': {('serie', 'subserie', 'tipo_documental')},
            },
        ),
        migrations.CreateModel(
            name='AuditoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_modificado', models.CharField(max_length=100, verbose_name='Campo modificado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor nuevo')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='correspondencia.documento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de documento',
                'verbose_name_plural': 'Auditorías de documentos',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['documento', 'fecha_hora'], name='corresponde_documen_751dd3_idx'), models.Index(fields=['usuario', 'fecha_hora'], name='corresponde_usuario_18a27e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccesoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('VER', 'Ver documento'), ('DESCARGAR', 'Descargar archivo'), ('IMPRIMIR', 'Imprimir documento'), ('EXPORTAR', 'Exportar reporte')], max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, max_length=500, verbose_name='User Agent')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='correspondencia.documento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso a documento',
                'verbose_name_plural': 'Accesos a documentos',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['documento', 'fecha_hora'], name='corresponde_documen_94e70e_idx'), models.Index(fields=['usuario', 'fecha_hora'], name='corresponde_usuario_f395a1_idx')],
            },
        ),
    ]
